name: 🪲 Bug Report
description: Report an issue with authenticus.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing an issue! If you are here to ask a question, use Discord instead: https://discord.gg/hrvetU2cJZ
  - type: dropdown
    id: preset
    attributes:
      label: Which preset is this for?
      options:
        - Discord
        - GitHub
        - GitLab
        - Google
        - LinkedIn
        - Spotify
        - Other
  - type: textarea
    id: code_sample
    attributes:
      label: Code sample
      description: |
        Your code sample should be:
        1. Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        2. Complete - Provide all parts someone else needs to reproduce your problem
        3. Reproducible - Test the code you're about to provide to make sure it reproduces the problem

        This will be automatically formatted into code, so no need for backticks.
      render: typescript
  - type: input
    id: version
    attributes:
      label: Version
      description: With which version of authenticus does this bug occur?
    validations:
      required: true
  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      options:
        - label: I made sure there's no open issue about this bug already.
